"use client";

import Link from "next/link";
import { BarChart3, Bot, CreditCard, LayoutDashboard, MessageSquare, Plus, Settings, Store, TrendingUp } from "lucide-react";
import { useState } from "react";

const bars = [32,44,39,55,48,65,57,71,64,82,74,91,79,96];
export function Dashboard() {
  const [active, setActive] = useState('Vue d’ensemble');
  const links = [['Vue d’ensemble',LayoutDashboard],['Mon analyste IA',MessageSquare],['Mes boutiques',Store],['Rapports',BarChart3],['Abonnement',CreditCard]] as const;
  return <main className="app-shell"><header className="app-header"><Link href="/" className="brand"><span className="brand-mark">✦</span><span className="brand-name">AI analyst <span>/ studio</span></span></Link><div className="app-user"><span style={{color:'#c4d7c9',fontSize:12}}>Bonjour, Aïcha</span><span className="avatar">AK</span></div></header><div className="app-layout"><aside className="sidebar"><div className="side-label">Workspace</div>{links.map(([name,Icon])=><button key={name} className={`side-link ${active===name?'active':''}`} onClick={()=>setActive(name)}><Icon size={16}/>{name}</button>)}<div className="side-label" style={{marginTop:28}}>Compte</div><button className="side-link"><Settings size={16}/>Paramètres</button><div style={{background:'#dcebd4',borderRadius:10,margin:'35px 4px 0',padding:14}}><span className="eyebrow" style={{fontSize:9}}>Plan Starter</span><p style={{fontSize:11,lineHeight:1.5,margin:'9px 0',color:'#55705d'}}>Passe au Pro pour débloquer les rapports.</p><button className="btn btn-dark" style={{fontSize:10,padding:'8px 10px',width:'100%'}}>Passer au Pro</button></div></aside><section className="app-main">{active==='Mon analyste IA'?<ChatView/>:active==='Mes boutiques'?<StoresView/>:active==='Abonnement'?<SubscriptionView/>:<Overview/>}</section></div></main>;
}
function Overview(){return <><div className="page-top"><div><span className="eyebrow">Mercredi 28 août 2026</span><h1>Vue d'ensemble</h1><p>Voici ce qui se passe dans ton business ce mois-ci.</p></div><button className="btn btn-dark"><Plus size={16}/> Connecter une boutique</button></div><div className="overview-grid"><div className="metric"><small>CA ce mois</small><strong>428 500 F</strong><span className="up">↑ 18,4% vs mois dernier</span></div><div className="metric"><small>Commandes</small><strong>86</strong><span className="up">↑ 12 nouvelles</span></div><div className="metric"><small>Panier moyen</small><strong>4 982 F</strong><span className="up">↑ 6,2% vs mois dernier</span></div><div className="metric"><small>Produit n°1</small><strong style={{fontSize:16}}>Vendre sur TikTok</strong><span className="up">62% de tes ventes</span></div></div><div className="content-grid"><div className="app-card"><div className="card-head"><div><h2>Evolution du chiffre d'affaires</h2><p>Les 30 derniers jours</p></div><select style={{border:'1px solid #dfe5de',borderRadius:6,padding:6,fontSize:10}}><option>Ce mois</option></select></div><div className="chart-large">{bars.map((height,i)=><i className="bar" key={i} style={{height:`${height}%`}}/>)}</div><div className="chart-labels"><span>01 août</span><span>08 août</span><span>15 août</span><span>22 août</span><span>Aujourd'hui</span></div></div><div className="app-card"><div className="card-head"><div><h2>Tes boutiques</h2><p>1 connexion active</p></div><button style={{background:'none',border:0,color:'#527767'}}><Plus size={17}/></button></div><div className="store-row"><div className="store-logo">C</div><div className="store-info"><strong>Aïcha Créations</strong><span>Chariow · connecté il y a 2 min</span></div><span className="status">● Active</span></div><div style={{borderTop:'1px solid #dfe5de',paddingTop:18,marginTop:15}}><div className="eyebrow" style={{fontSize:9}}>Usage IA ce mois</div><div className="usage"><div className="ring"><strong>287</strong></div><div className="usage-copy"><strong>287 / 400</strong><span>messages utilisés</span></div></div><div className="progress"><i/></div><p style={{color:'#809087',fontSize:10}}>Il te reste 113 messages ce mois-ci.</p></div></div></div><div className="app-card" style={{marginTop:16}}><div className="card-head"><div><h2>Dernières activités</h2><p>Les interactions récentes de ton espace</p></div><button className="btn btn-ghost" style={{fontSize:10,padding:'8px 12px'}}>Voir tout</button></div><ul className="activity"><li><i/><span><b>Analyse terminée</b> · Ton produit « Vendre sur TikTok » domine les ventes.<br/><small>Il y a 12 minutes</small></span></li><li><i/><span><b>Nouvelle commande</b> · Ebook Instagram reçu par Chariow.<br/><small>Il y a 34 minutes</small></span></li></ul></div></>}
function ChatView(){const [sent,setSent]=useState(false);return <><div className="page-top"><div><span className="eyebrow">Ton analyste IA</span><h1>On regarde ça ensemble ?</h1><p>Pose une question sur tes ventes, tes produits ou ta stratégie.</p></div></div><div className="app-card" style={{maxWidth:760,minHeight:480,display:'flex',flexDirection:'column'}}><div style={{background:'#edf6e8',borderRadius:8,padding:16,fontSize:13,lineHeight:1.6,maxWidth:570}}><b style={{display:'block',color:'#31593e',marginBottom:6}}>✦ AI Analyst</b>Bonjour Aïcha. J'ai analysé tes données de ce mois. Ton chiffre d'affaires progresse de 18,4%, porté principalement par <b>Vendre sur TikTok</b>. Que veux-tu explorer ?</div>{sent&&<div style={{alignSelf:'flex-end',background:'#234d3d',borderRadius:8,color:'white',fontSize:13,marginTop:18,padding:14}}>Comment augmenter mon panier moyen ?</div>}<div style={{marginTop:'auto'}}><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:15}}>{['Voir mes ventes','Analyser mes produits','Idées de bundle'].map(x=><button key={x} className="btn btn-ghost" onClick={()=>setSent(true)} style={{fontSize:11,padding:'9px 12px'}}>{x}</button>)}</div><div style={{border:'1px solid #dfe5de',borderRadius:8,display:'flex',padding:6}}><input placeholder="Pose ta question..." style={{border:0,flex:1,outline:0,padding:8,fontSize:12}}/><button className="btn btn-dark" onClick={()=>setSent(true)} style={{borderRadius:6,fontSize:11,padding:'9px 14px'}}>Envoyer</button></div></div></div></>}
function StoresView(){return <><div className="page-top"><div><span className="eyebrow">Connexions</span><h1>Mes boutiques</h1><p>Une source de vérité pour toutes tes ventes.</p></div><button className="btn btn-dark"><Plus size={16}/> Connecter</button></div><div className="app-card" style={{maxWidth:760}}><div className="store-row"><div className="store-logo">C</div><div className="store-info"><strong>Aïcha Créations</strong><span>Chariow · https://aichacreations.chariow.com</span></div><span className="status">● Active</span><button className="btn btn-ghost" style={{fontSize:10,padding:'7px 10px'}}>Gérer</button></div><div style={{border:'1px dashed #cdd9cd',borderRadius:9,marginTop:18,padding:28,textAlign:'center'}}><Store size={24} color="#6d9072"/><p style={{fontSize:13,margin:'10px 0 3px'}}>Ajoute une autre boutique</p><span style={{color:'#819087',fontSize:11}}>Bientôt disponible pour Selar et Gumroad.</span></div></div></>}
function SubscriptionView(){return <><div className="page-top"><div><span className="eyebrow">Ton abonnement</span><h1>Grandis à ton rythme.</h1><p>Gère ton plan et ton usage IA depuis un seul endroit.</p></div></div><div className="pricing-wrap" style={{maxWidth:800}}><article className="price-card"><span className="eyebrow">Plan actuel</span><h3>Starter</h3><div className="price">3 000 F <small>/ mois</small></div><ul><li>✓ 400 messages IA / mois</li><li>✓ 1 boutique connectée</li><li>✓ Support standard</li></ul><button className="btn btn-ghost" style={{width:'100%'}}>Gérer mon abonnement</button></article><article className="price-card pro"><span className="pill" style={{marginBottom:18}}>Recommandé</span><h3>Pro</h3><div className="price">5 000 F <small>/ mois</small></div><ul><li>✓ 1 200 messages IA / mois</li><li>✓ Jusqu'à 3 boutiques</li><li>✓ Rapports automatiques</li><li>✓ Support prioritaire</li></ul><button className="btn btn-lime" style={{width:'100%'}}>Passer au Pro</button></article></div></>}
