"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, ChevronDown } from "lucide-react";
import { useState } from "react";

const faqs = [
  ["Est-ce que je dois installer quelque chose ?", "Non. Tout se passe dans ton navigateur, sur ordinateur ou mobile. Connecte ta boutique et commence à poser tes questions."],
  ["Quelles plateformes sont compatibles ?", "Chariow est disponible au lancement. Selar, Gumroad et d'autres plateformes arriveront progressivement."],
  ["Que se passe-t-il si j'atteins ma limite ?", "Les messages sont bloqués jusqu'au renouvellement de ton abonnement. Tu peux aussi passer au plan Pro à tout moment."],
  ["Est-ce que mes données sont en sécurité ?", "Tes tokens sont chiffrés et tes données servent uniquement à produire les analyses demandées dans ton espace."],
  ["Puis-je annuler mon abonnement ?", "Oui, tu peux annuler ou changer de plan depuis ton espace, sans frais cachés."],
];

function Preview() {
  return <div className="dashboard-preview">
    <Image className="platform-preview-image" src="/vendeo-platform-preview.png" alt="Aperçu de la plateforme Vendeo" width={900} height={620} priority />
  </div>;
}

export function Marketing() {
  const [open, setOpen] = useState<number | null>(null);
  return <main>
      <header className="marketing-header"><div className="container"><nav className="marketing-nav"><Link href="/" className="brand"><Image className="brand-logo" src="/vendeo-logo-light.svg" alt="Vendeo" width={150} height={40}/></Link><div className="nav-links"><a href="#fonctionnalites">Fonctionnalités</a><a href="#comment">Comment ça marche</a><a href="#tarifs">Tarifs</a><a href="#faq">FAQ</a></div><Link className="btn btn-white" href="/register">Commencer <ArrowRight size={15}/></Link></nav></div></header>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="pill"><i className="dot"/> L'IA qui connaît ton business</span><h1>Arrête de deviner.<br/><em>Commence à décider.</em></h1><p>Ton analyste IA connecté à ta boutique. Comprends tes ventes, repère tes opportunités et sache exactement quoi faire ensuite.</p><div className="hero-actions"><Link href="/register" className="btn btn-lime">Créer mon espace gratuitement <ArrowRight size={16}/></Link><a href="#comment" className="btn" style={{border:'1px solid rgba(255,255,255,.3)',color:'white'}}>Voir comment ça marche</a></div><div className="hero-note">✓ Aucune installation &nbsp; · &nbsp; ✓ Connecté en 2 minutes &nbsp; · &nbsp; ✓ Pensé pour l'Afrique</div></div><Preview/></div></section>
     <div className="container"><div className="logos glass-strip"><span>CHARIOW</span><span>SELAR <small style={{fontWeight:400}}>(bientôt)</small></span><span>GUMROAD <small style={{fontWeight:400}}>(bientôt)</small></span><span>POUR LES CRÉATEURS</span></div></div>
     <section className="section" id="comment"><div className="container"><div className="section-head"><div><span className="eyebrow">Simple par design</span><h2>De tes données<br/>à tes décisions.</h2></div><p>Pas de tableaux compliqués. Pas de jargon. Vendeo transforme tes ventes en réponses claires et en actions concrètes.</p></div><div className="how-grid"><article className="step-card"><span className="step-num mono">01 / CONNECTER</span><h3>Ta boutique</h3><p>Branche Chariow en quelques clics. Tes données restent à toi.</p></article><article className="step-card"><span className="step-num mono">02 / DEMANDER</span><h3>Ta question</h3><p>Écris comme tu parles. L'IA comprend ton contexte et tes objectifs.</p></article><article className="step-card"><span className="step-num mono">03 / COMPRENDRE</span><h3>Ton insight</h3><p>Découvre ce qui marche, ce qui bloque et ce qui mérite ton attention.</p></article><article className="step-card"><span className="step-num mono">04 / AGIR</span><h3>Ton prochain move</h3><p>Obtiens une recommandation précise, pas une réponse générique.</p></article></div></div></section>
    <section className="section features-section" id="fonctionnalites"><div className="container"><div className="section-head"><div><span className="eyebrow">Pas juste un chatbot</span><h2>Un copilote pour<br/>ton business.</h2></div><p>Il ne se contente pas de regarder tes chiffres. Il t'aide à les utiliser pour vendre plus intelligemment.</p></div><div className="feature-grid"><article className="feature-card dark"><h3>Pose n'importe quelle question.</h3><p>Du chiffre d'affaires à ta prochaine campagne, ton analyste a les données et le contexte pour te répondre.</p><ul className="mini-list"><li>« Quel produit se vend le mieux ? »</li><li>« Comment augmenter mon panier moyen ? »</li><li>« Donne-moi une idée de bundle. »</li></ul></article><article className="feature-card light"><h3>Vois les opportunités avant les autres.</h3><p>Les tendances de tes ventes deviennent des décisions simples à prendre.</p><div className="feature-line"/></article></div></div></section>
    <section className="section" id="tarifs"><div className="container"><div className="section-head"><div><span className="eyebrow">Des prix qui ont du sens</span><h2>Commence petit.<br/>Grandis serein.</h2></div><p>Tout ce qu'il faut pour comprendre ton activité, sans abonnement hors-sol.</p></div><div className="pricing-wrap"><article className="price-card"><span className="eyebrow">Pour commencer</span><h3>Starter</h3><div className="price">3 000 F <small>/ mois</small></div><ul><li><Check className="check" size={15}/>400 messages IA / mois</li><li><Check className="check" size={15}/>1 boutique Chariow</li><li><Check className="check" size={15}/>Questions sur ventes et produits</li><li><Check className="check" size={15}/>Support standard</li></ul><Link href="/register" className="btn btn-dark" style={{width:'100%'}}>Choisir Starter <ArrowRight size={15}/></Link></article><article className="price-card pro"><span className="pill" style={{marginBottom:18}}>Le plus choisi</span><h3>Pro</h3><div className="price">5 000 F <small>/ mois</small></div><ul><li><Check className="check" size={15}/>1 200 messages IA / mois</li><li><Check className="check" size={15}/>Jusqu'à 3 boutiques</li><li><Check className="check" size={15}/>Stratégie, pricing et promotions</li><li><Check className="check" size={15}/>Rapports automatiques</li><li><Check className="check" size={15}/>Support prioritaire</li></ul><Link href="/register" className="btn btn-lime" style={{width:'100%'}}>Choisir Pro <ArrowRight size={15}/></Link></article></div></div></section>
    <section className="section" id="faq"><div className="container"><div className="section-head"><div><span className="eyebrow">Questions fréquentes</span><h2>Tout est<br/>plus clair.</h2></div><p>Une question que tu ne vois pas ici ? Écris-nous, on te répond.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className="faq-item" key={q}><button className="faq-question" onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}>{q}<span>{open===i?'−':'+'}</span></button>{open===i&&<div className="faq-answer">{a}</div>}</div>)}</div></div></section>
    <section className="section" style={{paddingTop:0}}><div className="container"><div className="cta"><span className="eyebrow">Ton prochain bon choix</span><h2>Tes ventes parlent déjà.<br/>Il est temps de les écouter.</h2><p>Connecte ta boutique et découvre ton premier insight en moins de 2 minutes.</p><Link href="/register" className="btn btn-dark">Créer mon espace <ArrowRight size={16}/></Link></div></div></section>
      <footer className="site-footer"><div className="container footer-row"><Link href="/" className="brand"><Image className="brand-logo" src="/vendeo-logo-light.svg" alt="Vendeo" width={150} height={40}/></Link><div className="footer-links"><a href="#faq">Confidentialité</a><a href="#faq">Conditions</a><a href="mailto:hello@vendeo.studio">Contact</a></div><span style={{color:'#91a3c8',fontSize:11}}>© 2026 Vendeo</span></div></footer>
  </main>;
}
